language: node_js
env:
- secure: "bpT79u10n+ktgsaZ2rT+FJRfGZ/kutl0uGkyBXjy6bX0Ef2dJF7GLZAx+4Wlnlb0M+jZda8Az1TfLlGD33Q496deNwYWf4RdiAd0PyXGJ+lEtpAt2nga+qvAkauoripCYoV/ovlXnGEBUA7AmHHcqIR4Rrqp5FocFppgzSg57hw="
services:
- couchdb
node_js:
- '0.11'
- '0.10'
after_success:
- npm install -g couchapp
- couchapp push couchapp.js $DEPLOY_TO
